# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.8

    branches:
      only:
        - master

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Setup Git
      - run:
          name: Setup Git
          command: |
            git config --global user.email "derekbwarren@gmail.com"
            git config --global user.name "Derek Warren"
            git remote rm origin
            git remote add origin https://derekbwarren:${GITHUB_TOKEN}@github.com/derekbwarren/ktb-frontend.git
      
      # Add ENV
      - run:
          name: Add ENV
          command: echo -e 'REACT_APP_BASENAME="/ktb-frontend/"\nREACT_APP_FIREBASE_KEY=${FIREBASE_KEY}\nREACT_APP_FIREBASE_DOMAIN=${FIREBASE_DOMAIN}\nREACT_APP_FIREBASE_DATABASE=${FIREBASE_DATABASE}\nREACT_APP_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}\nREACT_APP_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}\nREACT_APP_FIREBASE_SENDER_ID=${FIREBASE_SENDER_ID}' > .env
      # Build Code
      - run:
          name: Build
          command: CI=false yarn build

      # Deploy Static files!
      - run:
          name: yarn deploy
          command: yarn deploy